name: mech_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  http: ^1.2.0  
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  image_picker: ^1.0.7
  
  
  

  # OTP field package
  pinput: ^6.0.1 

  # Google Fonts package flu
  

  google_sign_in: ^7.2.0 
  

  
  geolocator: ^14.0.2 
  
  # Google Maps integration ke liye 
  google_maps_flutter: ^2.5.3
  # For free map (OpenStreetMap) integration
 # flutter_map: ^8.2.2
  #latlong2: ^0.9.0
  location: ^8.0.1
 # flutter_map: ^3.1.0
  latlong2: ^0.8.1

  # Cupertino Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

    - family: LuckiestGuy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Bold.ttf
          weight: 700